#!/usr/bin/env bash
#
# changelog.sh — Generate a structured CHANGELOG.md from git history
#
# Usage: ./changelog.sh [options]
#   --since-tag <tag>   Start from a specific tag (default: last tag)
#   --output <file>    Output file (default: CHANGELOG.md)
#   --dry-run          Preview to stdout instead of writing file
#   --all              Include all commits (not just since last tag)
#   --repo <path>      Target repo path (default: current dir)
#   -h, --help         Show this help
#
# Requirements: git, bash
#

set -euo pipefail

OUTPUT="CHANGELOG.md"
SINCE_TAG=""
DRY_RUN=false
INCLUDE_ALL=false
REPO_PATH="."

while [[ $# -gt 0 ]]; do
  case "$1" in
    --since-tag)  SINCE_TAG="$2"; shift 2 ;;
    --output)    OUTPUT="$2"; shift 2 ;;
    --dry-run)   DRY_RUN=true; shift ;;
    --all)       INCLUDE_ALL=true; shift ;;
    --repo)      REPO_PATH="$2"; shift 2 ;;
    -h|--help)
      sed -n '3,$p' "$0" | head -20
      exit 0 ;;
    *) echo "Unknown option: $1" >&2; exit 1 ;;
  esac
done

cd "$REPO_PATH"

# Determine commit range
if [[ "$INCLUDE_ALL" == true ]]; then
  RANGE="--all"
elif [[ -n "$SINCE_TAG" ]]; then
  RANGE="${SINCE_TAG}..HEAD"
elif git describe --tags --abbrev=0 &>/dev/null; then
  LAST_TAG=$(git describe --tags --abbrev=0)
  RANGE="${LAST_TAG}..HEAD"
else
  RANGE="HEAD"
fi

TODAY=$(date +%Y-%m-%d)

# Fetch commits, one per line, no duplicates
mapfile -t COMMITS < <(git log $RANGE --pretty=format:'%s' 2>/dev/null | \
  awk '!seen[$0]++' | tac)

# Categorize commits
ADDED=()
FIXED=()
CHANGED=()
REMOVED=()

categorize() {
  local msg="$1"
  local upper
  upper=$(echo "$msg" | tr '[:lower:]' '[:upper:]')

  # Breaking changes → Removed
  if echo "$upper" | grep -q 'BREAKING CHANGE'; then
    REMOVED+=("$msg")
  # feat → Added
  elif echo "$msg" | grep -qE '^(feat|feature)(\(|:|$)'; then
    ADDED+=("$msg")
  # fix → Fixed
  elif echo "$msg" | grep -qE '^(fix|hotfix)(\(|:|$)'; then
    FIXED+=("$msg")
  # chore/docs/style/refactor/perf/test/build/ci/revert → Changed
  elif echo "$msg" | grep -qE '^(chore|docs|style|refactor|perf|test|build|ci|revert|init)(\(|:|$)'; then
    CHANGED+=("$msg")
  # Other → Changed
  else
    CHANGED+=("$msg")
  fi
}

for commit in "${COMMITS[@]}"; do
  [[ -z "$commit" ]] && continue
  categorize "$commit"
done

# Build CHANGELOG
build_section() {
  local label="$1"; shift
  local -n arr="$1"
  if [[ ${#arr[@]} -gt 0 ]]; then
    echo ""
    echo "### ${label}"
    for item in "${arr[@]}"; do
      echo "- ${item}"
    done
  fi
}

CHANGELOG="# Changelog

All notable changes to this project will be documented in this file.

## [Unreleased] - ${TODAY}
$(build_section "Added" ADDED)
$(build_section "Fixed" FIXED)
$(build_section "Changed" CHANGED)
$(build_section "Removed" REMOVED)

---

*Generated by \`changelog.sh\` — https://github.com/claude-builders-bounty/claude-builders-bounty*
"

if [[ "$DRY_RUN" == true ]]; then
  echo "$CHANGELOG"
else
  echo "$CHANGELOG" > "$OUTPUT"
  echo "✅ CHANGELOG.md written to $OUTPUT ($(wc -l < "$OUTPUT") lines)"
fi
