#!/bin/bash
#============================================================
# changelog.sh — Generate CHANGELOG.md from git history
# Usage: bash changelog.sh [--from-tag <tag>] [--output <file>]
#============================================================

set -euo pipefail

OUTPUT_FILE="${OUTPUT_FILE:-CHANGELOG.md}"
SINCE_TAG=""
PROJECT_NAME=$(basename "$(git rev-parse --show-toplevel 2>/dev/null || echo "$PWD")")

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --from-tag) SINCE_TAG="$2"; shift 2 ;;
    --output) OUTPUT_FILE="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Check git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "Error: Not a git repository"
  exit 1
fi

# Detect last tag
if [[ -z "$SINCE_TAG" ]]; then
  SINCE_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
fi

# Determine range
if [[ -n "$SINCE_TAG" ]]; then
  RANGE="$SINCE_TAG..HEAD"
  SECTION_HEADER="## [$SINCE_TAG]"
else
  RANGE="--all"
  SINCE_TAG="Unreleased"
  SECTION_HEADER="## [Unreleased]"
fi

# Category arrays
declare -A ADDED FIXED CHANGED REMOVED

# Categorize a commit message
categorize() {
  local msg="$1"
  local lower_msg=$(echo "$msg" | tr '[:upper:]' '[:lower:]')

  if echo "$lower_msg" | grep -qE '(add|feat|new|introduce|create|init|implement)'; then
    echo "ADDED"
  elif echo "$lower_msg" | grep -qE '(fix|bug|patch|repair|correct|hotfix|resolve)'; then
    echo "FIXED"
  elif echo "$lower_msg" | grep -qE '(remove|delete|drop|deprecate|uninstall|cleanup|rm)'; then
    echo "REMOVED"
  elif echo "$lower_msg" | grep -qE '(change|update|modify|refactor|improve|optimize|upgrade|upgrade|revise)'; then
    echo "CHANGED"
  else
    echo "CHANGED"
  fi
}

# Collect commits
echo "Generating changelog from: ${RANGE}..."

while IFS='||' read -r subject body _; do
  [[ -z "$subject" ]] && continue

  # Skip merge commits
  [[ "$subject" =~ ^Merge ]] && continue

  # Skip tag commits
  [[ "$subject" =~ ^ tagged ]] && continue

  category=$(categorize "$subject")
  entry="- $subject"

  case $category in
    ADDED)   ADDED["$entry"]=1 ;;
    FIXED)   FIXED["$entry"]=1 ;;
    CHANGED) CHANGED["$entry"]=1 ;;
    REMOVED) REMOVED["$entry"]=1 ;;
  esac
done < <(git log "$RANGE" --pretty=format:"%s||%b||%H" 2>/dev/null)

# Check if we have any changes
if [[ ${#ADDED[@]} == 0 && ${#FIXED[@]} == 0 && ${#CHANGED[@]} == 0 && ${#REMOVED[@]} == 0 ]]; then
  echo "No commits found in range: $RANGE"
  exit 2
fi

# Generate changelog
{
  echo "# Changelog"
  echo ""
  echo "All notable changes to this project will be documented in this file."
  echo ""
  echo "This changelog is automatically generated by \`changelog.sh\`."
  echo ""
  echo "$SECTION_HEADER"
  echo ""
  
  if [[ ${#ADDED[@]} -gt 0 ]]; then
    echo "### Added"
    echo ""
    printf '%s\n' "${!ADDED[@]}" | sort
    echo ""
  fi
  
  if [[ ${#FIXED[@]} -gt 0 ]]; then
    echo "### Fixed"
    echo ""
    printf '%s\n' "${!FIXED[@]}" | sort
    echo ""
  fi
  
  if [[ ${#CHANGED[@]} -gt 0 ]]; then
    echo "### Changed"
    echo ""
    printf '%s\n' "${!CHANGED[@]}" | sort
    echo ""
  fi
  
  if [[ ${#REMOVED[@]} -gt 0 ]]; then
    echo "### Removed"
    echo ""
    printf '%s\n' "${!REMOVED[@]}" | sort
    echo ""
  fi
  
  # Append old changelog if exists
  if [[ -f "$OUTPUT_FILE" ]]; then
    # Find where to split (after the first H2 or H1 header)
    local_lines=$(awk '/^##? /{if(NR>1)print; found=1; exit} found{print}' "$OUTPUT_FILE" | tail -n +2)
    if [[ -n "$local_lines" ]]; then
      echo "---"
      echo ""
      echo "## History"
      echo ""
      echo "$local_lines"
    fi
  fi
} > "$OUTPUT_FILE.tmp"

mv "$OUTPUT_FILE.tmp" "$OUTPUT_FILE"

echo "✅ CHANGELOG.md generated successfully: $OUTPUT_FILE"
echo ""
echo "Summary:"
[[ ${#ADDED[@]} -gt 0 ]] && echo "  Added:   ${#ADDED[@]}"
[[ ${#FIXED[@]} -gt 0 ]] && echo "  Fixed:   ${#FIXED[@]}"
[[ ${#CHANGED[@]} -gt 0 ]] && echo "  Changed: ${#CHANGED[@]}"
[[ ${#REMOVED[@]} -gt 0 ]] && echo "  Removed: ${#REMOVED[@]}"
