#!/bin/bash
# claude-review — PR reviewer agent that analyzes a PR diff and returns structured Markdown review
# Usage: claude-review --pr https://github.com/owner/repo/pull/123
#        claude-review --diff ./diff.txt

set -e

parse_args() {
    PR_URL=""
    DIFF_FILE=""
    
    while [[ $# -gt 0 ]]; do
        case $1 in
            --pr)
                PR_URL="$2"
                shift 2
                ;;
            --diff)
                DIFF_FILE="$2"
                shift 2
                ;;
            *)
                shift
                ;;
        esac
    done
}

fetch_pr_diff() {
    local url="$1"
    # Extract owner, repo, pr_number from URL like https://github.com/owner/repo/pull/123
    if [[ "$url" =~ github\.com/([^/]+)/([^/]+)/pull/([0-9]+) ]]; then
        local owner="${BASH_REMATCH[1]}"
        local repo="${BASH_REMATCH[2]}"
        local pr_num="${BASH_REMATCH[3]}"
        gh api "repos/$owner/$repo/pulls/$pr_num" --jq '.body, .title, .user.login' > /tmp/pr_meta_$$.txt 2>/dev/null || true
        gh api "repos/$owner/$repo/pulls/$pr_num/files" > /tmp/pr_diff_$$.txt 2>/dev/null || true
        echo "/tmp/pr_diff_$$.txt"
    else
        echo ""
    fi
}

analyze_diff() {
    local diff_path="$1"
    if [[ ! -s "$diff_path" ]]; then
        echo "## PR Review\n\n⚠️ Could not fetch PR diff. Please provide a valid PR URL or diff file."
        exit 1
    fi
    
    local diff_content=$(cat "$diff_path")
    local lines=$(echo "$diff_content" | wc -l)
    local files_changed=$(echo "$diff_content" | grep "^diff --git" | wc -l)
    local additions=$(echo "$diff_content" | grep "^+" | grep -v "^+++" | wc -l)
    local deletions=$(echo "$diff_content" | grep "^-" | grep -v "^---" | wc -l)
    
    # Simple heuristic analysis
    local risks=""
    local suggestions=""
    local confidence="Medium"
    
    # Check for security concerns
    if echo "$diff_content" | grep -Ei "password|secret|api_key|token|aws_key" > /dev/null; then
        risks+="- ⚠️ Potential hardcoded credentials detected — verify they're not real secrets\n"
        confidence="Low"
    fi
    
    # Check for large diffs
    if [[ $lines -gt 2000 ]]; then
        risks+="- ⚠️ Large diff ($lines lines) — consider splitting into smaller PRs\n"
    fi
    
    # Check for SQL
    if echo "$diff_content" | grep -Ei "DROP\s+TABLE|TRUNCATE|ALTER\s+TABLE\s+.*\s+DELETE" > /dev/null; then
        risks+="- ⚠️ Database schema changes detected — ensure proper backup and migration plan\n"
        confidence="Low"
    fi
    
    # Check for dependency changes
    if echo "$diff_content" | grep -E "^(--- a/|\+\+\+ b/).*package" > /dev/null; then
        suggestions+="- 📦 Dependency changes detected — verify lockfile was also updated\n"
    fi
    
    # General suggestions
    if ! echo "$diff_content" | grep -Ei "test" > /dev/null; then
        suggestions+="- 🧪 No test changes detected — consider adding tests for new functionality\n"
    fi
    
    suggestions+="- 📝 Ensure CHANGELOG or release notes are updated for user-facing changes\n"
    suggestions+="- 🔍 Review error handling for new API endpoints or database operations\n"
    
    # Output structured review
    cat << EOF
## PR Review

### Summary
This PR modifies $files_changed file(s) with approximately $(( additions - files_changed )) additions and $(( deletions - files_changed )) deletions across $lines lines of diff.

EOF

    if [[ -n "$risks" ]]; then
        echo "### 🚨 Identified Risks"
        echo -e "$risks"
        echo ""
    fi
    
    echo "### 💡 Improvement Suggestions"
    echo -e "$suggestions"
    echo ""
    
    echo "### Confidence Score: $confidence"
    echo ""
    echo "---"
    echo "*Generated by claude-review agent*"
}

main() {
    parse_args "$@"
    
    if [[ -n "$DIFF_FILE" ]]; then
        analyze_diff "$DIFF_FILE"
    elif [[ -n "$PR_URL" ]]; then
        diff_path=$(fetch_pr_diff "$PR_URL")
        if [[ -z "$diff_path" ]]; then
            echo "Error: Invalid PR URL format"
            exit 1
        fi
        analyze_diff "$diff_path"
    else
        echo "Usage: claude-review --pr https://github.com/owner/repo/pull/123"
        echo "       claude-review --diff ./diff.txt"
        exit 1
    fi
}

main "$@"
