#!/bin/bash
#============================================================
# changelog.sh — Generate CHANGELOG.md from git history
# Usage: bash changelog.sh [--from-tag <tag>] [--output <file>]
#============================================================

OUTPUT_FILE="${OUTPUT_FILE:-CHANGELOG.md}"
SINCE_TAG=""

# Parse args
while [[ $# -gt 0 ]]; do
  case $1 in
    --from-tag|--from) SINCE_TAG="$2"; shift 2 ;;
    --output|-o) OUTPUT_FILE="$2"; shift 2 ;;
    *) echo "Unknown option: $1"; exit 1 ;;
  esac
done

# Check git repo
if ! git rev-parse --git-dir > /dev/null 2>&1; then
  echo "Error: Not a git repository"
  exit 1
fi

# Detect last tag
if [[ -z "$SINCE_TAG" ]]; then
  LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
else
  LAST_TAG="$SINCE_TAG"
fi

# Determine range and header
if [[ -n "$LAST_TAG" ]]; then
  RANGE="$LAST_TAG..HEAD"
  SECTION_HEADER="## [$LAST_TAG]"
  DATE_HEADER=$(date +%Y-%m-%d)
else
  RANGE="--all"
  SECTION_HEADER="## [Unreleased]"
  DATE_HEADER=$(date +%Y-%m-%d)
fi

# Temp files for categorized commits
TMP_ADDED=$(mktemp)
TMP_FIXED=$(mktemp)
TMP_CHANGED=$(mktemp)
TMP_REMOVED=$(mktemp)
TMP_OTHER=$(mktemp)
trap 'rm -f "$TMP_ADDED" "$TMP_FIXED" "$TMP_CHANGED" "$TMP_REMOVED" "$TMP_OTHER"' EXIT

# Categorize a commit message
categorize() {
  local msg="$1"
  local lower_msg
  lower_msg=$(printf '%s' "$msg" | tr '[:upper:]' '[:lower:]')

  if printf '%s' "$lower_msg" | grep -qE '(add|feat|new|introduce|create|init|implement)'; then
    echo "ADDED"
  elif printf '%s' "$lower_msg" | grep -qE '(fix|bug|patch|repair|correct|hotfix|resolve)'; then
    echo "FIXED"
  elif printf '%s' "$lower_msg" | grep -qE '(remove|delete|drop|deprecate|uninstall|cleanup)[[:space:]]'; then
    echo "REMOVED"
  elif printf '%s' "$lower_msg" | grep -qE '(change|update|modify|refactor|improve|optimize|upgrade|deprecate)'; then
    echo "CHANGED"
  else
    echo "OTHER"
  fi
}

# Collect commits
echo "Generating changelog from: ${RANGE}..."

while IFS= read -r subject; do
  # Skip merge commits
  case "$subject" in Merge*|*merge*) continue ;; esac
  # Skip empty
  [[ -z "$subject" ]] && continue

  category=$(categorize "$subject")
  entry="- $subject"

  case "$category" in
    ADDED)   echo "$entry" >> "$TMP_ADDED" ;;
    FIXED)   echo "$entry" >> "$TMP_FIXED" ;;
    CHANGED) echo "$entry" >> "$TMP_CHANGED" ;;
    REMOVED) echo "$entry" >> "$TMP_REMOVED" ;;
    OTHER)   echo "$entry" >> "$TMP_OTHER" ;;
  esac
done < <(git log "$RANGE" --pretty=format:"%s" 2>/dev/null)

# Check if we have any changes
if [[ ! -s "$TMP_ADDED" && ! -s "$TMP_FIXED" && ! -s "$TMP_CHANGED" && ! -s "$TMP_REMOVED" && ! -s "$TMP_OTHER" ]]; then
  echo "No commits found in range: $RANGE"
  exit 2
fi

# Sort and deduplicate
sort_dedup() {
  local file="$1"
  if [[ ! -s "$file" ]]; then
    return
  fi
  sort "$file" | uniq
}

# Count lines
count_lines() {
  local file="$1"
  if [[ ! -s "$file" ]]; then
    echo 0
  else
    wc -l < "$file" | tr -d ' '
  fi
}

NUM_ADDED=$(count_lines "$TMP_ADDED")
NUM_FIXED=$(count_lines "$TMP_FIXED")
NUM_CHANGED=$(count_lines "$TMP_CHANGED")
NUM_REMOVED=$(count_lines "$TMP_REMOVED")
NUM_OTHER=$(count_lines "$TMP_OTHER")

# Generate changelog
{
  echo "# Changelog"
  echo ""
  echo "All notable changes to this project will be documented in this file."
  echo ""
  echo "This changelog is automatically generated by \`changelog.sh\`."
  echo ""
  echo "$SECTION_HEADER - $DATE_HEADER"
  echo ""
  
  if [[ -s "$TMP_ADDED" ]]; then
    echo "### Added"
    echo ""
    sort_dedup "$TMP_ADDED"
    echo ""
  fi
  
  if [[ -s "$TMP_FIXED" ]]; then
    echo "### Fixed"
    echo ""
    sort_dedup "$TMP_FIXED"
    echo ""
  fi
  
  if [[ -s "$TMP_CHANGED" ]]; then
    echo "### Changed"
    echo ""
    sort_dedup "$TMP_CHANGED"
    echo ""
  fi
  
  if [[ -s "$TMP_REMOVED" ]]; then
    echo "### Removed"
    echo ""
    sort_dedup "$TMP_REMOVED"
    echo ""
  fi
  
  if [[ -s "$TMP_OTHER" ]]; then
    echo "### Other"
    echo ""
    sort_dedup "$TMP_OTHER"
    echo ""
  fi
} > "$OUTPUT_FILE"

echo "✅ CHANGELOG.md generated: $OUTPUT_FILE"
echo ""
echo "Summary:"
echo "  Added:   $NUM_ADDED"
echo "  Fixed:   $NUM_FIXED"
echo "  Changed: $NUM_CHANGED"
echo "  Removed: $NUM_REMOVED"
echo "  Other:   $NUM_OTHER"